277 solutions rewrite
dataquestio/solutions pull request #126
Opened 2020-09-09 01:22 UTC by thecbp

2020-09-10 00:38 UTC, Casey-Bates requested changes
Hey @thecbp. Comments provided for the Guided Project. Please address the comments and send back to me for another review. I will review the Jupyter Notebook for the Guided Project during my second review.

Some students use Guided Projects for portfolios, so it's important that the Guided Project results in plots that have intuitive graphics. This was also stressed in the course. The solutions proposed in this Guided Project for reordering bars results in x-axes that are not intuitive. 

Also, the amount of code required for `case_when()` far exceeds that of setting factor levels one time in the R Markdown notebook. This needs to be fixed. Especially because using `case_when()` in the context of ggplots was not taught in the course. I think sticking with the factors wording that Rose wrote for 277.4 is probably the best way to go given the nature of this dataset. Also, the mutate call to convert the `month` and `day` columns to factors is relatively concise.

Please let me know if you have any questions or if you want to discuss anything.

2020-09-10 00:38 UTC, Casey-Bates commented on Mission277Solutions.Rmd
> +
**Must fix**: The default plot size for this facet_grid plot is cluttered. Give the students a hint/suggestion in the Guided Project that they can play around with plot size in the options section of an R Markdown cell. [Cite this as a reference](https://r4ds.had.co.nz/graphics-for-communication.html#figure-sizing) and then they can pursue this on their own if they wish.

<img width="796" alt="Screen Shot 2020-09-09 at 6 14 37 PM" src="https://user-images.githubusercontent.com/38499910/92667427-22896780-f2c9-11ea-8561-bd601473ad5c.png">

2020-09-10 00:38 UTC, Casey-Bates commented on Mission277Solutions.Rmd
> +    month_num = case_when(
Code repetition. If this approach is used, it should be used only once to modify the original dataframe (like with the factors approach).

2020-09-10 05:48 UTC, thecbp commented on Mission277Solutions.Rmd
Hey Casey, I get what you mean (related to overall comment on GP solutions). I wasn't sure what the best way to approach the mission was because I checked that factors were not taught in John's course. Factors would fix most of the problems, but I wanted to confirm with you that I'm able to teach this new material in a GP. I'm more than happy to write up a quick tutorial screen, but my understanding was that new material should not be taught.

2020-09-10 13:04 UTC, Casey-Bates commented on Mission277Solutions.Rmd
Hey Christian. You are correct, new material should not be taught in a GP. Thanks for being mindful of that. Unfortunately, in this situation, we're inheriting a GP that was authored before this convention was established. The GP is solid overall, and will be better now that learners work with `facet_grid()`, but yeah, that means we need to teach (1) factors and (2) mention/teach`scales = "free_x"` somewhere in the course or GP. Also, mentioning that resizing the figure to make it more readable is a "nice to have".

I'm open to however you want to do it. I think the brief write-up on factors that [Rose wrote in 277.4](https://app.dataquest.io/m/277/guided-project%3A-analyzing-forest-fire-data/4/working-with-factor-data) is adequate. But if you think you can fit it into a single screen in M276, I'm open to that as well. But I don't know if it's a natural fit for that dataset. I think that the reference that Rose included for factors is pretty good, but there's always [Hadley](https://r4ds.had.co.nz/factors.html) as well. 

Thanks, and let me know if you want to toss around ideas for where in our content we teach factors.

2020-09-10 20:54 UTC, thecbp commented on Mission277Solutions.Rmd
Thanks Casey, I think I know how to get around the issue. I think  I'll teach factors in one of the earlier missions at least, probably using the movie dataset. Having access to factors should make everything more concise, so I'll work on these and will ping you when I've finished it up.

2020-09-10 21:07 UTC, Casey-Bates commented on Mission277Solutions.Rmd
Thanks, Christian! Sounds great. If you can fit it into one of the earlier missions that would be ideal because students will use factors again in the Intro Stats course, so it will be great for them to see it in the learning content. And its useful info for ggplots. Thanks!

2020-09-18 16:24 UTC, Casey-Bates approved these changes
Looks awesome @thecbp ! Love the updates. I will merge this PR when I deploy the optimization. No further action required from you on this at the moment.

2020-09-21 21:56 UTC, merged